### PR TITLE
Better formatting of javascript errors

### PR DESCRIPTION
**Pull request by aiba**
I think in javascript land, we want to show the stringified error (which contains the type of error and err.message, both important pieces of info) as well as the stacktrace if it exists.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Looks good, thanks Aaron! Am hoping to get a chance to cut a new release this weekend. Cheers :-)

**Comment by DerGuteMoritz** [comment]
Just happened upon this issue. Since the code comment still asks for alternatives, I would like to mention the formatting function we've been using quite successfully so far:

```clojure
(defn format-error [err]
  (str (.-stack err) ; includes `ex-message`
       (when-let [d (ex-data err)]
         (str "\nex-data\n    " (pr-str d)))
       (when-let [c (ex-cause err)]
         (str "\ncaused by - " (format-error c)))))
```

As you can see, it also walks the cause chain and prints `ex-data`.

**Comment by aiba** [comment]
@DerGuteMoritz yeah this function is even better.  Do you want to submit a PR for this, or if you'd like I can copy/paste it into my PR.

**Comment by DerGuteMoritz** [comment]
Sure thing, here you go! Adjusted it to also use `enc/system-newline`.

**Pull request closed without merging**
