### PR TITLE
Adds a `:flush?` option for logstash appender

### PR DESCRIPTION
**Pull request by tvanhens**
Setting the value to true will eagerly flush the tcp writer. Default
behavior is for this to be false.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Merged, thanks Tyler.

**Comment by tvanhens** [comment]
Is there a new clojars deploy for timbre slated any time soon?

**Comment by ptaoussanis** [comment]
Just pushed `[com.taoensso/timbre "4.8.0-alpha1"]` to Clojars for you, cheers :-)

**Comment by tvanhens** [comment]
Amazing, thanks!

**Pull request closed without merging**
