### PR TITLE
Feature/appender postgresdb

### PR DESCRIPTION
**Pull request by yuliu-mdsol**

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hi there! Just checking: is there a reason you closed this PR or would you still like me to merge?

**Comment by yuliu-mdsol** [comment]
Hi Peter:

I recently changed from Lein to Boot so the database migration needs to be
changed. The migratus plug only works for Lein and I am testing ragtime for
database migration in Boot. I will adjust document string and then resubmit
PR.

Thanks,
Yue


On Thu, Mar 24, 2016 at 12:38 AM, Peter Taoussanis <notifications@github.com

**Comment by ptaoussanis** [comment]
Sounds good, thanks for the update!

**Comment by yuliu-mdsol** [comment]
PR is submitted with description in docstring.

Yue

**Pull request closed without merging**
